project:
  type: book
  output-dir: docs

book:
  title: "Measurement, Experimentation, & Causal Inference"
  subtitle: "Advanced Methods Workshop · RSM"
  author: "Dan Schley"
  date: today
  repo-url: https://github.com/DanRSchley/Measurement-Experimentation-and-Causal-Inference-Workshop
  repo-actions: [issue]
  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd
    - part: "Module 1: Measurement"
      chapters:
        - module-1/intro.qmd
        - module-1/case1.qmd
        - module-1/case2.qmd
        - module-1/case3.qmd
        - module-1/case4.qmd
        - module-1/case5.qmd
        - module-1/case6.qmd
    - part: "Module 2: Hypothesis Testing"
      chapters:
        - module-2/intro.qmd
        - module-2/part1.qmd
        - module-2/part2.qmd
        - module-2/part3.qmd
        - module-2/part4.qmd
    - part: "Module 3: Causal Inference"
      chapters:
        - module-3/intro.qmd
        - module-3/part1.qmd
        - module-3/part2.qmd
        - module-3/part3.qmd
        - module-3/part4.qmd
        - module-3/part5.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-tools:
      source: false
      toggle: true
      caption: "Show/Hide All Code"
    highlight-style: github
    df-print: kable

execute:
  warning: false
  message: false
  freeze: auto
